- name: Create vm
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
   - var

  tasks:

   - name: Launch instances
     gce:
         instance_names: jenkins
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
     register: gce
 
   - name: Wait for SSH to come up
     wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60 #state=started
     with_items: "{{ gce.instance_data }}"

   - name: Add host to groupname
     add_host: hostname={{ item.public_ip }} groupname=new_instances
     with_items: "{{ gce.instance_data }}"

   - name: Allow HTTP traffic
     gce_net:
         fwname: pass-http
         name: default
         allowed: tcp:8080
         project_id: "{{ project_id }}"
         credentials_file: "{{ credentials_file }}"
         service_account_email: "{{ service_account_email }}"

   - name: Allow HTTP traffic
     gce_net:
         fwname: pass2-http
         name: default
         allowed: tcp:8090
         project_id: "{{ project_id }}"
         credentials_file: "{{ credentials_file }}"
         service_account_email: "{{ service_account_email }}"


   - name: Allow HTTPS traffic
     gce_net:
         fwname: pass-https
         name: default
         allowed: tcp:8090
         project_id: "{{ project_id }}"
         credentials_file: "{{ credentials_file }}"
         service_account_email: "{{ service_account_email }}"

   - name: Allow HTTPS traffic
     gce_net:
         fwname: pass2-https
         name: default
         allowed: tcp:8080
         project_id: "{{ project_id }}"
         credentials_file: "{{ credentials_file }}"
         service_account_email: "{{ service_account_email }}"

- name: Manage new instances
  hosts: new_instances
  connection: ssh
  sudo: True
  gather_facts: yes

  roles:
    - base_configuration
    - jenkins_run
